### ISSUE TITLE
Unable to run docker with dart cloud function in ARM machine (M1 Mac)

### ISSUE THREAD

**Issue by happyharis** [dart-lang/dart-docker#32] opened 2021-06-07 10:37 UTC
Was following [Quickstart: Docker](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/docs/quickstarts/02-quickstart-docker.md) instructions under functions-framework-dart. 

Downloaded the [hello world project](https://github.com/GoogleCloudPlatform/functions-framework-dart/archive/main.zip) and ran `docker build -t hellofunc .`

Expected: No errors

Reality: Error found.

<details>
  <summary>Logs</summary>

```
haris@Hariss-MacBook-Air functions-framework-dart-main % docker build -t hellofunc .
[+] Building 4.1s (16/18)                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 119B                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 2B                                                                                                             0.0s
 => [internal] load metadata for docker.io/subfuzion/dart:slim                                                                              2.5s
 => [internal] load metadata for docker.io/google/dart:2.12                                                                                 2.5s
 => CACHED [stage-1 1/2] FROM docker.io/subfuzion/dart:slim@sha256:1a60fa1089065c4dd86d0735becafab9d14dca828ba0ee19ab6b547c9e81e479         0.0s
 => [stage-0  1/11] FROM docker.io/google/dart:2.12@sha256:e058e2a4d9dbae12771cea71846be1695bd0012879f7de98617495cc235355d9                 0.0s
 => [internal] load build context                                                                                                           0.0s
 => => transferring context: 58.53kB                                                                                                        0.0s
 => CACHED [stage-0  2/11] WORKDIR /app                                                                                                     0.0s
 => CACHED [stage-0  3/11] COPY ./functions_framework/pubspec.yaml /app/functions_framework/                                                0.0s
 => CACHED [stage-0  4/11] COPY ./functions_framework_builder/pubspec.yaml /app/functions_framework_builder/                                0.0s
 => CACHED [stage-0  5/11] COPY ./test/hello/pubspec.yaml /app/test/hello/                                                                  0.0s
 => CACHED [stage-0  6/11] WORKDIR /app/test/hello                                                                                          0.0s
 => CACHED [stage-0  7/11] RUN dart pub get                                                                                                 0.0s
 => CACHED [stage-0  8/11] COPY . ../..                                                                                                     0.0s
 => CACHED [stage-0  9/11] RUN dart pub get --offline                                                                                       0.0s
 => ERROR [stage-0 10/11] RUN dart pub run build_runner build --delete-conflicting-outputs                                                  1.5s
------                                                                                                                                           
 > [stage-0 10/11] RUN dart pub run build_runner build --delete-conflicting-outputs:                                                             
#16 1.463 
#16 1.463 ===== CRASH =====
#16 1.463 si_signo=Segmentation fault(11), si_code=1, si_addr=0xffffffffffffff90
#16 1.463 version=2.12.4 (stable) (Unknown timestamp) on "linux_x64"
#16 1.464 pid=10, thread=18, isolate_group=dartdev(0x4002c44000), isolate=dartdev(0x4002be9000)
#16 1.464 isolate_instructions=400648e000, vm_instructions=4001a0f020
#16 1.464   pc 0x000000400450a711 fp 0x0000004009210590 Unknown symbol
#16 1.465   pc 0x0000004008cc32b0 fp 0x00000040092105f8 Unknown symbol
#16 1.465   pc 0x0000004008cc3037 fp 0x0000004009210678 Unknown symbol
#16 1.465   pc 0x0000004008cc2ddd fp 0x00000040092106f0 Unknown symbol
#16 1.465   pc 0x0000004008cc1dfe fp 0x0000004009210768 Unknown symbol
#16 1.465   pc 0x0000004008cc14c0 fp 0x00000040092107e0 Unknown symbol
#16 1.465   pc 0x0000004008cc0e2f fp 0x0000004009210860 Unknown symbol
#16 1.465   pc 0x0000004008cc0aac fp 0x00000040092108d8 Unknown symbol
#16 1.465   pc 0x0000004008cc08a9 fp 0x0000004009210930 Unknown symbol
#16 1.465   pc 0x0000004008cc0419 fp 0x00000040092109d0 Unknown symbol
#16 1.465   pc 0x0000004008cbe818 fp 0x0000004009210a60 Unknown symbol
#16 1.465   pc 0x0000004008cbe414 fp 0x0000004009210ab0 Unknown symbol
#16 1.465   pc 0x000000400b0b2c81 fp 0x0000004009210b08 Unknown symbol
#16 1.465   pc 0x000000400b09dfdf fp 0x0000004009210b80 Unknown symbol
#16 1.465   pc 0x000000400b09bead fp 0x0000004009210c18 Unknown symbol
#16 1.465   pc 0x000000400b09b6c4 fp 0x0000004009210c70 Unknown symbol
#16 1.465   pc 0x0000004008cf712a fp 0x0000004009210d00 Unknown symbol
#16 1.465   pc 0x0000004008cf6925 fp 0x0000004009210db8 Unknown symbol
#16 1.465   pc 0x0000004008cb3e2b fp 0x0000004009210e78 Unknown symbol
#16 1.465   pc 0x0000004008cb79dc fp 0x0000004009210ef0 Unknown symbol
#16 1.465   pc 0x0000004008cb787c fp 0x0000004009210f58 Unknown symbol
#16 1.465   pc 0x0000004008cb753c fp 0x0000004009210ff8 Unknown symbol
#16 1.465   pc 0x000000400651946e fp 0x0000004009211048 Unknown symbol
#16 1.465   pc 0x000000400651ae9e fp 0x00000040092110a8 Unknown symbol
#16 1.465   pc 0x000000400651a3c2 fp 0x0000004009211130 Unknown symbol
#16 1.465   pc 0x000000400651c51b fp 0x0000004009211178 Unknown symbol
#16 1.465   pc 0x0000004006535a5e fp 0x00000040092111b8 Unknown symbol
#16 1.465   pc 0x0000004008cb4c7c fp 0x0000004009211258 Unknown symbol
#16 1.465   pc 0x0000004008cb79dc fp 0x00000040092112d0 Unknown symbol
#16 1.465   pc 0x0000004008cb787c fp 0x0000004009211338 Unknown symbol
#16 1.465   pc 0x0000004008cb753c fp 0x00000040092113d8 Unknown symbol
#16 1.465   pc 0x000000400651946e fp 0x0000004009211428 Unknown symbol
#16 1.465   pc 0x000000400651ae9e fp 0x0000004009211488 Unknown symbol
#16 1.465   pc 0x000000400651a3c2 fp 0x0000004009211510 Unknown symbol
#16 1.465   pc 0x0000004008cb7378 fp 0x0000004009211550 Unknown symbol
#16 1.465   pc 0x0000004008cb1a3d fp 0x00000040092115c0 Unknown symbol
#16 1.465   pc 0x0000004008cb17b9 fp 0x0000004009211620 Unknown symbol
#16 1.465   pc 0x0000004008cb10d9 fp 0x00000040092116b8 Unknown symbol
#16 1.465   pc 0x0000004008cb724f fp 0x0000004009211728 Unknown symbol
#16 1.465   pc 0x0000004008cb714d fp 0x0000004009211768 Unknown symbol
#16 1.465   pc 0x000000400651dd37 fp 0x00000040092117b0 Unknown symbol
#16 1.465   pc 0x000000400651e12e fp 0x00000040092117f0 Unknown symbol
#16 1.465   pc 0x000000400651e359 fp 0x0000004009211818 Unknown symbol
#16 1.465   pc 0x00000040065358bd fp 0x0000004009211858 Unknown symbol
#16 1.465   pc 0x00000040065363f7 fp 0x0000004009211880 Unknown symbol
#16 1.465   pc 0x000000400470265f fp 0x00000040092118f8 Unknown symbol
#16 1.468   pc 0x0000004001ba7690 fp 0x0000004009211990 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x110
#16 1.469   pc 0x0000004001ba74c5 fp 0x00000040092119f0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x175
#16 1.469   pc 0x0000004001ba9e1e fp 0x0000004009211a40 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x1ee
#16 1.470   pc 0x0000004001bd1d42 fp 0x0000004009211c30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x4d2
#16 1.470   pc 0x0000004001bfe106 fp 0x0000004009211ca0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x146
#16 1.470   pc 0x0000004001bfe7ba fp 0x0000004009211d00 dart::MessageHandler::TaskCallback()+0x1da
#16 1.471   pc 0x0000004001d0c708 fp 0x0000004009211d80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
#16 1.471   pc 0x0000004001d0cbdc fp 0x0000004009211db0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
#16 1.472   pc 0x0000004001c8421d fp 0x0000004009211e70 /usr/lib/dart/bin/dart+0x1c8421d
#16 1.472 -- End of DumpStackTrace
#16 1.472 qemu: uncaught target signal 6 (Aborted) - core dumped
#16 1.482 Aborted
------
executor failed running [/bin/sh -c dart pub run build_runner build --delete-conflicting-outputs]: exit code: 134

```

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.3.1 20E241 darwin-arm, locale en-SG)
    • Flutter version 2.2.1 at /Users/haris/Development/flutter
    • Framework revision 02c026b03c (11 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/haris/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.3.1 20E241 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.77

• No issues found!

```

</details>

**Comment by athomas** [comment] 2021-10-12 14:33
Duplicate of #11.

**Closed by athomas** 2021-10-12 14:33 UTC
Labels: duplicate
